var annotated_dup =
[
    [ "Chest", "class_chest.html", "class_chest" ],
    [ "CombatSystem", "class_combat_system.html", "class_combat_system" ],
    [ "DialogChoice", "struct_dialog_choice.html", "struct_dialog_choice" ],
    [ "DialogNode", "struct_dialog_node.html", "struct_dialog_node" ],
    [ "DialogOutcome", "struct_dialog_outcome.html", "struct_dialog_outcome" ],
    [ "DialogTree", "class_dialog_tree.html", "class_dialog_tree" ],
    [ "Door", "class_door.html", "class_door" ],
    [ "Enemy", "class_enemy.html", "class_enemy" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "Inventory", "class_inventory.html", "class_inventory" ],
    [ "Item", "class_item.html", "class_item" ],
    [ "Location", "class_location.html", "class_location" ],
    [ "LocationFactory", "class_location_factory.html", "class_location_factory" ],
    [ "LockpickPuzzle", "class_lockpick_puzzle.html", "class_lockpick_puzzle" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "Map", "class_map.html", "class_map" ],
    [ "MapChestSpawn", "struct_map_chest_spawn.html", "struct_map_chest_spawn" ],
    [ "MapEnemySpawn", "struct_map_enemy_spawn.html", "struct_map_enemy_spawn" ],
    [ "MapNpcSpawn", "struct_map_npc_spawn.html", "struct_map_npc_spawn" ],
    [ "MathPuzzle", "class_math_puzzle.html", "class_math_puzzle" ],
    [ "Npc", "class_npc.html", "class_npc" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Potion", "class_potion.html", "class_potion" ],
    [ "Puzzle", "class_puzzle.html", "class_puzzle" ],
    [ "RiddlePuzzle", "class_riddle_puzzle.html", "class_riddle_puzzle" ],
    [ "SaveManager", "class_save_manager.html", "class_save_manager" ],
    [ "Weapon", "class_weapon.html", "class_weapon" ]
];